<?php
namespace App\Http\Controllers\Frontend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
class FrontendController extends Controller
{
    private function webp($path)
    {
        return str_replace(
            'frontend/assets/img/projects/lokruproject/',
            'frontend/assets/img/projects/lokruprojectwebp/',
            preg_replace('/\.(png|jpg|jpeg)$/i', '.webp', $path)
        );
    }
    private function getProjects()
    {
        $projects = [
            // ==========================================================
            // TIER 1 — Full-stack, real-world/business systems
            // (Laravel/PHP + MySQL, live demos, payments, dashboards)
            // ==========================================================
            [
                'id' => 17,
                'title' => 'E-Pharmacy Platform',
                'client' => 'Academic Project',
                'role' => 'Full Stack Developer',
                'date' => 'July, 2026',
                'service' => 'Web Application Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'Bootstrap',
                    'JavaScript',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/e-phamacy2.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/e-phamacy2.png',
                    'frontend/assets/img/projects/lokruproject/e-phamacy1.png',
                    'frontend/assets/img/projects/lokruproject/e-phamacy3.png',
                ],
                'description' => 'A modern online pharmacy platform that allows customers to browse medicines, upload prescriptions, place orders, and choose between home delivery or store pickup. The system also includes secure payment options and an admin management dashboard.',
                'background' => 'The project was developed to digitalize pharmacy services, making it easier for customers to purchase medicines online while allowing pharmacy staff to efficiently manage products, prescriptions, and customer orders.',
                'challenges' => 'Designing a secure and user-friendly platform that supports prescription uploads, inventory management, online payments, and order tracking while maintaining a responsive experience across all devices.',
                'solution' => 'Built a full-stack web application with customer and administrator features, including medicine catalog management, prescription verification, KHQR payment support, Telegram notifications, and order management.',
                'demo_url' => 'https://e-pharmacy.xyz/',
                'github_url' => null, // Add later if the repository becomes public
                'figma_url' => null,
                'technologies' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'Bootstrap 5',
                    'JavaScript',
                    'KHQR',
                    'Telegram API',
                    'Git',
                ],
            ],
            [
                'id' => 21,
                'title' => 'ICT Professional Training Center (LMS)',
                'client' => 'ICT Professional Training Center',
                'role' => 'Full Stack Developer',
                'date' => '2026',
                'service' => 'Learning Management System (LMS)',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'Bootstrap',
                    'JavaScript',
                    'LMS',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/ictcenterblog1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/ictcenterblog1.png',
                    'frontend/assets/img/projects/lokruproject/ictcenterblog2.png',
                    'frontend/assets/img/projects/lokruproject/ictcenterblog3.png',
                ],
                'description' => 'A complete Learning Management System (LMS) developed for ICT Professional Training Center. The platform enables students to explore courses, register online, manage enrollments, and access training information through a modern and responsive interface.',
                'background' => 'The project was built to digitalize the training center by replacing manual registration and course management with an integrated online platform for students, instructors, and administrators.',
                'challenges' => 'Developing a scalable system capable of managing courses, schedules, instructors, student registrations, authentication, and administrative workflows while maintaining an intuitive user experience.',
                'solution' => 'Built a full-stack Laravel application with responsive frontend pages, course management, instructor profiles, authentication, enrollment management, and an administrator dashboard for managing training operations.',
                'demo_url' => 'https://ictcenter.blog/',
                'github_url' => null,
                'figma_url' => null,
                'technologies' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'Bootstrap 5',
                    'JavaScript',
                    'Blade',
                    'Authentication',
                    'Git',
                ],
                'features' => [
                    'Course Management',
                    'Student Registration',
                    'Course Enrollment',
                    'Instructor Profiles',
                    'Training Schedules',
                    'Authentication',
                    'Responsive Design',
                    'Admin Dashboard',
                ],
            ],
            [
                'id' => 14,
                'title' => 'Pharmacare management system',
                'client' => 'Local Client',
                'date' => 'February, 2025',
                'service' => 'Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Web', 'Management'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/pharmacare1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/pharmacare1.png',
                    'frontend/assets/img/projects/lokruproject/pharmacare2.png',
                    'frontend/assets/img/projects/lokruproject/pharmacare3.png',
                    'frontend/assets/img/projects/lokruproject/pharmacare4.png',
                    'frontend/assets/img/projects/lokruproject/pharmacare6.png',
                    'frontend/assets/img/projects/lokruproject/pharmacaredashboard.png',
                    'frontend/assets/img/projects/lokruproject/pharmacarelogin.png',
                ],
                'description' => 'A pharmacy management system for handling medicine inventory, patient records, and sales tracking.',
                'background' => 'The client needed a digital system to manage their pharmacy operations and reduce manual paperwork.',
                'challenges' => 'Designing an intuitive interface for pharmacy staff to quickly search, manage, and track medicine stock.',
                'solution' => 'Built a full-featured pharmacy management system with a dashboard, login system, inventory management, and sales reporting.',
                'demo_url' => 'https://sophearagit.github.io/phamacare/',
                'github_url' => 'https://github.com/sinethV/website-phamarcy.git',
                'figma_url' => null,
            ],

            // ==========================================================
            // TIER 2 — Frontend/React projects with real demo + repo
            // (fully documented: live site + source code)
            // ==========================================================
            [
                'id' => 1,
                'title' => 'ICT Tech Company Website',
                'client' => 'Team Project',
                'date' => 'June, 2025',
                'service' => 'Frontend Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'HTML',
                    'CSS',
                    'JavaScript',
                    'Bootstrap'
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/ict-tech1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/ict-tech1.png',
                    'frontend/assets/img/projects/lokruproject/ict-tech2.png',
                    'frontend/assets/img/projects/lokruproject/ict-tech3.png',
                    'frontend/assets/img/projects/lokruproject/ict-tech4.png',
                    'frontend/assets/img/projects/lokruproject/ict-tech-admin1.png',
                    'frontend/assets/img/projects/lokruproject/ict-tech-admin2.png',
                ],
                'description' => 'A responsive company website developed for an ICT technology business. The project includes a modern landing page, service pages, and an administrative interface with a clean and user-friendly design.',
                'background' => 'The goal of this project was to build a professional company website that showcases ICT services while providing an easy-to-manage administration interface.',
                'challenges' => 'Creating a responsive layout that works across desktop, tablet, and mobile devices while maintaining a consistent user experience throughout the public website and admin pages.',
                'solution' => 'Developed a responsive website using HTML, CSS, JavaScript, and Bootstrap with an intuitive UI, organized navigation, and dedicated admin pages for managing website content.',
                'demo_url' => 'https://sophearagit.github.io/ict-tech/index.html',
                'github_url' => 'https://github.com/SophearaGit/ict-tech/tree/thon',
                'figma_url' => 'https://www.figma.com/design/UvztL57BiGLPRvMj843I05/Untitled?node-id=0-1&p=f&t=rkHcvO9LRLQ1r9NU-0',
                'technologies' => [
                    'HTML5',
                    'CSS3',
                    'JavaScript',
                    'Bootstrap 5',
                    'Git',
                    'GitHub'
                ],
            ],
            [
                'id' => 16,
                'title' => 'Energy Tracker - Solar Energy Website',
                'client' => 'Academic Project',
                'role' => 'Frontend Developer',
                'date' => 'June, 2025',
                'service' => 'Frontend Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'HTML',
                    'CSS',
                    'JavaScript',
                    'Bootstrap',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/energysolarict1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/energysolarict1.png',
                    'frontend/assets/img/projects/lokruproject/energysolarict2.png',
                ],
                'description' => 'A responsive solar energy website that promotes renewable energy solutions and provides users with information about solar products, services, and sustainable energy technologies.',
                'background' => 'The project was developed as part of an academic team project to demonstrate modern frontend development practices while raising awareness of renewable energy solutions.',
                'challenges' => 'Building a responsive interface with an attractive user experience while organizing multiple sections, animations, and navigation into a clean, maintainable structure.',
                'solution' => 'Developed a responsive frontend using HTML, CSS, JavaScript, and Bootstrap with modern UI components, smooth navigation, and mobile-friendly layouts.',
                'demo_url' => 'https://sophearagit.github.io/solar-energy-ict/',
                'github_url' => 'https://github.com/Oeungsovannaroth/EnergyTrackerFront_end',
                'figma_url' => null,
                'technologies' => [
                    'HTML5',
                    'CSS3',
                    'JavaScript',
                    'Bootstrap 5',
                    'Git',
                    'GitHub',
                ],
            ],
            [
                'id' => 13,
                'title' => 'ICT React web application',
                'client' => 'Local Client',
                'date' => 'January, 2025',
                'service' => 'Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Web', 'React'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/ictreact1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/ictreact1.png',
                    'frontend/assets/img/projects/lokruproject/ictreact2.png',
                    'frontend/assets/img/projects/lokruproject/ictreact3.png',
                    'frontend/assets/img/projects/lokruproject/ictreact4.png',
                ],
                'description' => 'A modern React-based web application built for an ICT company with a clean and responsive interface.',
                'background' => 'The client needed a fast, modern web presence built with React to showcase their ICT services.',
                'challenges' => 'Structuring reusable components while maintaining a consistent design system across all pages.',
                'solution' => 'Developed a component-driven React application with a clean UI, smooth navigation, and fully responsive layout.',
                'demo_url' => 'https://ict-omega.vercel.app/',
                'github_url' => 'https://github.com/ChanVimean/ICT',
                'figma_url' => null,
            ],
            [
                'id' => 18,
                'title' => 'Tech Girl Store',
                'client' => 'Personal Project',
                'role' => 'Frontend Developer',
                'date' => 'July, 2026',
                'service' => 'Frontend Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'React',
                    'JavaScript',
                    'Bootstrap',
                    'E-Commerce',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/techgirlstore1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/techgirlstore1.png',
                    'frontend/assets/img/projects/lokruproject/techgirlstore2.png',
                    'frontend/assets/img/projects/lokruproject/techgirlstore3.png',
                    'frontend/assets/img/projects/lokruproject/techgirlstore4.png',
                ],
                'description' => 'A modern online technology store built with React, featuring a clean shopping experience, responsive layouts, and organized product categories for browsing computer hardware and accessories.',
                'background' => 'This project was created to practice modern frontend development by building an attractive and responsive e-commerce interface for technology products.',
                'challenges' => 'Creating reusable React components, maintaining consistent styling across multiple pages, and ensuring a smooth user experience on desktop and mobile devices.',
                'solution' => 'Developed a responsive React application with reusable components, intuitive navigation, organized product displays, and a modern shopping interface optimized for all screen sizes.',
                'demo_url' => 'https://tech-girl-store.vercel.app/#about',
                'github_url' => 'https://github.com/SophearaGit/tech-girl-store',
                'figma_url' => null,
                'technologies' => [
                    'React',
                    'JavaScript',
                    'Bootstrap',
                    'HTML5',
                    'CSS3',
                    'Git',
                    'GitHub',
                    'Vercel',
                ],
            ],

            // ==========================================================
            // TIER 3 — Frontend/React projects with live demo only
            // (no public repo linked)
            // ==========================================================
            [
                'id' => 20,
                'title' => 'ICT Solution Company Website',
                'client' => 'ICT Solution',
                'role' => 'Frontend Developer',
                'date' => 'August, 2026',
                'service' => 'Corporate Website Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'HTML',
                    'CSS',
                    'JavaScript',
                    'Bootstrap',
                    'Responsive',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/ict-solution-1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/ict-solution-1.png',
                    'frontend/assets/img/projects/lokruproject/ict-solution-2.png',
                    'frontend/assets/img/projects/lokruproject/ict-solution-3.png',
                    'frontend/assets/img/projects/lokruproject/ict-solution-4.png',
                ],
                'description' => 'A modern corporate website developed for an ICT solutions company to showcase its services, technology expertise, completed projects, and contact information. The website features a clean interface, responsive design, and professional branding.',
                'background' => 'The objective of this project was to establish a professional online presence for an ICT solutions company, allowing potential clients to easily explore its services and business information.',
                'challenges' => 'Creating a professional business website that is visually appealing, responsive across all devices, and easy for visitors to navigate while maintaining fast loading performance.',
                'solution' => 'Developed a responsive company website with organized service sections, project showcases, contact information, and a modern user interface that enhances the company’s digital presence.',
                'demo_url' => 'https://ict-solution.ictcenter.blog/',
                'github_url' => null,
                'figma_url' => null,
                'technologies' => [
                    'HTML5',
                    'CSS3',
                    'JavaScript',
                    'Bootstrap 5',
                    'Git',
                    'Responsive Design',
                ],
            ],
            [
                'id' => 22,
                'title' => 'ZipBuy E-Commerce Platform',
                'client' => 'Personal Project',
                'role' => 'Frontend Developer',
                'date' => '2026',
                'service' => 'E-Commerce Website Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'React',
                    'JavaScript',
                    'Bootstrap',
                    'E-Commerce',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/zipbuy1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/zipbuy1.png',
                    'frontend/assets/img/projects/lokruproject/zipbuy2.png',
                    'frontend/assets/img/projects/lokruproject/zipbuy3.png',
                    'frontend/assets/img/projects/lokruproject/zipbuy4.png',
                    'frontend/assets/img/projects/lokruproject/zipbuy5.png',
                ],
                'description' => 'A modern e-commerce platform that provides customers with an intuitive shopping experience for browsing products, exploring categories, and discovering featured collections through a clean and responsive user interface.',
                'background' => 'The project was developed to practice modern React development while building a professional online shopping experience with responsive layouts and reusable components.',
                'challenges' => 'Designing a scalable frontend architecture with reusable components, responsive layouts, and smooth navigation while maintaining a consistent user experience across all devices.',
                'solution' => 'Built a responsive React-based e-commerce application with organized product displays, reusable UI components, category browsing, and an attractive modern shopping interface.',
                'demo_url' => 'https://zipbuy-delta.vercel.app/',
                'github_url' => null,
                'figma_url' => null,
                'technologies' => [
                    'React',
                    'JavaScript',
                    'Bootstrap 5',
                    'HTML5',
                    'CSS3',
                    'Git',
                    'Vercel',
                ],
                'features' => [
                    'Responsive Design',
                    'Product Catalog',
                    'Category Browsing',
                    'Featured Products',
                    'Modern UI',
                    'Reusable Components',
                ],
            ],
            [
                'id' => 23,
                'title' => 'Prime Real Estate Website',
                'client' => 'Personal Project',
                'role' => 'Frontend Developer',
                'date' => '2026',
                'service' => 'Real Estate Website Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'React',
                    'JavaScript',
                    'Bootstrap',
                    'Real Estate',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/prime.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/prime.png',
                    'frontend/assets/img/projects/lokruproject/prime1.png',
                    'frontend/assets/img/projects/lokruproject/prime2.png',
                    'frontend/assets/img/projects/lokruproject/prime3.png',
                    'frontend/assets/img/projects/lokruproject/prime4.png',
                    'frontend/assets/img/projects/lokruproject/prime5.png',
                    'frontend/assets/img/projects/lokruproject/prime6.png',
                ],
                'description' => 'A modern real estate website designed to showcase residential and commercial properties through an attractive, responsive, and user-friendly interface. The platform focuses on delivering a seamless browsing experience for potential buyers and property investors.',
                'background' => 'The project was created to practice modern frontend development by building a professional real estate platform with clean layouts, reusable components, and responsive design.',
                'challenges' => 'Creating an elegant property showcase while maintaining fast performance, responsive layouts, and a consistent user experience across different screen sizes.',
                'solution' => 'Developed a responsive React-based website featuring modern UI components, organized property listings, engaging hero sections, and intuitive navigation to enhance the user experience.',
                'demo_url' => 'https://ngaisov-project.vercel.app/',
                'github_url' => null,
                'figma_url' => null,
                'technologies' => [
                    'React',
                    'JavaScript',
                    'Bootstrap 5',
                    'HTML5',
                    'CSS3',
                    'Git',
                    'Vercel',
                ],
                'features' => [
                    'Responsive Design',
                    'Property Listings',
                    'Modern Landing Page',
                    'Reusable Components',
                    'Interactive UI',
                    'Cross-device Compatibility',
                ],
            ],
            [
                'id' => 24,
                'title' => 'UC Glamour Fashion Store',
                'client' => 'Personal Project',
                'role' => 'Frontend Developer',
                'date' => '2026',
                'service' => 'Fashion E-Commerce Website',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'React',
                    'E-Commerce',
                    'Fashion',
                    'Bootstrap',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/glamour.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/glamour.png',
                    'frontend/assets/img/projects/lokruproject/glamour1.png',
                    'frontend/assets/img/projects/lokruproject/glamour2.png',
                ],
                'description' => 'A modern fashion e-commerce website designed to showcase clothing and lifestyle products through an elegant, responsive, and user-friendly shopping experience. The interface emphasizes clean layouts, featured collections, and seamless product browsing.',
                'background' => 'The project was developed to practice modern frontend development while creating a stylish online fashion store with a focus on usability, responsive design, and attractive product presentation.',
                'challenges' => 'Designing a visually appealing shopping experience that balances aesthetics with usability while maintaining responsive layouts across desktop, tablet, and mobile devices.',
                'solution' => 'Built a responsive React-based fashion store featuring reusable components, organized product collections, promotional sections, and an intuitive navigation system for a smooth user experience.',
                'demo_url' => 'https://uc-glamour.vercel.app/',
                'github_url' => null,
                'figma_url' => null,
                'technologies' => [
                    'React',
                    'JavaScript',
                    'Bootstrap 5',
                    'HTML5',
                    'CSS3',
                    'Git',
                    'Vercel',
                ],
                'features' => [
                    'Responsive Design',
                    'Fashion Catalog',
                    'Featured Collections',
                    'Modern Landing Page',
                    'Reusable Components',
                    'Cross-device Compatibility',
                ],
            ],
            [
                'id' => 19,
                'title' => 'Phone Store Cambodia',
                'client' => 'Academic Project',
                'role' => 'Frontend Developer',
                'date' => 'July, 2026',
                'service' => 'Frontend Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => [
                    'React',
                    'E-Commerce',
                    'Bootstrap',
                    'JavaScript',
                ],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/phonestore1.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/phonestore1.png',
                    'frontend/assets/img/projects/lokruproject/phonestore2.png',
                    'frontend/assets/img/projects/lokruproject/phonestore3.png',
                ],
                'description' => 'A modern e-commerce website for browsing and exploring smartphones, accessories, and technology products. The application features a clean interface, responsive design, and an organized shopping experience.',
                'background' => 'The project was developed to create a responsive online phone store that showcases mobile devices and accessories while providing users with an intuitive browsing experience.',
                'challenges' => 'Designing a responsive product catalog with reusable components, maintaining a consistent layout, and optimizing the interface for desktop and mobile users.',
                'solution' => 'Built a responsive frontend application with organized product listings, modern UI components, category navigation, and an engaging shopping experience across all screen sizes.',
                'demo_url' => 'https://cambo.phonestore.rith.codes/',
                'github_url' => null, // Add if you have access to the repository
                'figma_url' => null,
                'technologies' => [
                    'React',
                    'JavaScript',
                    'Bootstrap',
                    'HTML5',
                    'CSS3',
                    'Git',
                ],
            ],

            // ==========================================================
            // TIER 4 — Earlier practice projects (no live demo, generic
            // placeholder repo link)
            // ==========================================================
            [
                'id' => 2,
                'title' => 'Hotel management system',
                'client' => 'Local Client',
                'date' => 'March, 2024',
                'service' => 'Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Web', 'Management'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/hotelmanagementsystem1.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/hotelmanagementsystem1.jpg',
                    'frontend/assets/img/projects/lokruproject/hotelmanagementsystem2.jpg',
                    'frontend/assets/img/projects/lokruproject/hotelmanagementsystem3.jpg',
                ],
                'description' => 'A hotel management system for handling room bookings, guest records, and staff operations.',
                'background' => 'The hotel needed a centralized system to replace manual paper-based processes.',
                'challenges' => 'Coordinating real-time room availability and booking conflicts across multiple room types.',
                'solution' => 'Developed a clean dashboard system with booking management, room status tracking, and reporting.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 3,
                'title' => 'Library management website',
                'client' => 'Local Client',
                'date' => 'April, 2024',
                'service' => 'Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Web', 'Software'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/libraryweb1.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/libraryweb1.jpg',
                    'frontend/assets/img/projects/lokruproject/libraryweb2.jpg',
                ],
                'description' => 'A digital library system for managing books, members, and borrow/return records.',
                'background' => 'The library wanted to modernize its catalog and lending process.',
                'challenges' => 'Building a search system that works fast across a large catalog of books and authors.',
                'solution' => 'Created a web-based system with member login, book search, and borrowing history tracking.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 6,
                'title' => 'Real estate platform',
                'client' => 'Local Client',
                'date' => 'July, 2024',
                'service' => 'Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Web', 'Design'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/realestate.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/realestate.jpg',
                ],
                'description' => 'A real estate listing platform for browsing properties with filters and contact forms.',
                'background' => 'The agency needed an online presence to showcase their property listings.',
                'challenges' => 'Making property search intuitive with filters for location, price, and property type.',
                'solution' => 'Built a responsive listing site with advanced filters, photo galleries, and inquiry forms.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 15,
                'title' => 'E-commerce web application',
                'client' => 'Local Client',
                'date' => 'January, 2024',
                'service' => 'Web Development',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['E-Commerce', 'Web'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/ecom.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/ecom.jpg',
                    'frontend/assets/img/projects/lokruproject/ecom1.jpg',
                    'frontend/assets/img/projects/lokruproject/ecom2.jpg',
                    'frontend/assets/img/projects/lokruproject/ecomlaptop.jpg',
                ],
                'description' => 'A full-featured e-commerce platform with product listings, shopping cart, and checkout flow.',
                'background' => 'The client needed an online store to expand their retail business digitally.',
                'challenges' => 'Designing a smooth user experience across both mobile and desktop while keeping performance high.',
                'solution' => 'Built a responsive e-commerce site with an intuitive UI, fast load times, and a simple checkout process.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 12,
                'title' => 'Personal portfolio website',
                'client' => 'Personal Project',
                'date' => 'December, 2024',
                'service' => 'Web Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Web', 'Design'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/portfolionhimnhanh.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/portfolionhimnhanh.jpg',
                ],
                'description' => 'A personal portfolio website showcasing design and development work.',
                'background' => 'Needed a professional online presence to present skills and past projects.',
                'challenges' => 'Making a portfolio that stands out while staying clean and easy to navigate.',
                'solution' => 'Designed and built a fast, minimal portfolio site with smooth navigation and clear project showcases.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],

            // ==========================================================
            // TIER 5 — UI/UX design-only projects (mobile app mockups)
            // ==========================================================
            [
                'id' => 7,
                'title' => 'ICT mobile app UI/UX',
                'client' => 'Local Client',
                'date' => 'August, 2024',
                'service' => 'UI/UX Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Mobile', 'UX/UI'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/uxuimobileict1.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/uxuimobileict1.jpg',
                    'frontend/assets/img/projects/lokruproject/uxuimobileict2.jpg',
                    'frontend/assets/img/projects/lokruproject/uxuimobileict3.jpg',
                ],
                'description' => 'A multi-screen mobile UI/UX design for an ICT services company.',
                'background' => 'The company needed a professional app design to present their services digitally.',
                'challenges' => 'Communicating complex technical services in a simple, approachable mobile layout.',
                'solution' => 'Designed a clean, professional app with clear service categories and easy contact flows.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 8,
                'title' => 'LMS mobile app UI/UX',
                'client' => 'Local Client',
                'date' => 'September, 2024',
                'service' => 'UI/UX Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Mobile', 'UX/UI'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/uxuimobilelms.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/uxuimobilelms.jpg',
                ],
                'description' => 'A learning management system mobile app design for students and instructors.',
                'background' => 'An education provider wanted a mobile-first LMS to reach more students.',
                'challenges' => 'Designing course navigation and progress tracking that feels simple for all age groups.',
                'solution' => 'Created an accessible, student-friendly UI with clear course layouts and progress indicators.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 4,
                'title' => 'Café mobile app UI/UX design',
                'client' => 'Local Client',
                'date' => 'May, 2024',
                'service' => 'UI/UX Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Mobile', 'UX/UI'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/uxuimobilecafe.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/uxuimobilecafe.jpg',
                ],
                'description' => 'A mobile app UI/UX design for a café, covering menu browsing, ordering, and loyalty features.',
                'background' => 'The café wanted a branded mobile experience to boost customer engagement.',
                'challenges' => 'Designing a warm, inviting interface that makes ordering feel effortless.',
                'solution' => 'Delivered high-fidelity Figma prototypes with a cozy color palette and smooth user flows.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 5,
                'title' => 'Restaurant mobile app UI/UX',
                'client' => 'Local Client',
                'date' => 'June, 2024',
                'service' => 'UI/UX Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Mobile', 'UX/UI'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/uxuimobilerestaurant.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/uxuimobilerestaurant.jpg',
                ],
                'description' => 'Mobile UI/UX design for a restaurant app with table reservations and digital menu.',
                'background' => 'The restaurant needed a modern app to streamline dine-in and takeaway ordering.',
                'challenges' => 'Balancing information density — menu items, prices, photos — without overwhelming users.',
                'solution' => 'Designed a clean, photo-first layout with clear category navigation and a simple cart flow.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],

            // ==========================================================
            // TIER 6 — Personal exploration & graphic design pieces
            // (lowest priority: not client work, no demo/repo)
            // ==========================================================
            [
                'id' => 9,
                'title' => 'Instagram mobile UI redesign',
                'client' => 'Personal Project',
                'date' => 'October, 2024',
                'service' => 'UI/UX Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Mobile', 'Design'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/uxuimobileinstagram.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/uxuimobileinstagram.jpg',
                ],
                'description' => 'A personal UI redesign concept for Instagram with a refreshed visual style.',
                'background' => 'A self-initiated project to explore modern social media UI patterns.',
                'challenges' => 'Reimagining a familiar app while keeping it instantly recognizable to existing users.',
                'solution' => 'Produced a concept redesign with cleaner typography, updated iconography, and improved spacing.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 10,
                'title' => 'Nivea product poster design',
                'client' => 'Personal Project',
                'date' => 'November, 2024',
                'service' => 'Graphic Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Design', 'Branding'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/niveaposter.jpg',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/niveaposter.jpg',
                ],
                'description' => 'A product poster design for Nivea with a clean, minimal aesthetic.',
                'background' => 'A graphic design exercise focused on product advertising and visual composition.',
                'challenges' => 'Balancing brand color guidelines with a fresh, eye-catching layout.',
                'solution' => 'Designed a minimal poster that highlights the product with strong typography and brand colors.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
            [
                'id' => 11,
                'title' => 'Pizza restaurant poster',
                'client' => 'Personal Project',
                'date' => 'November, 2024',
                'service' => 'Graphic Design',
                'address' => 'Phnom Penh, Cambodia',
                'tags' => ['Design', 'Branding'],
                'thumbnail' => 'frontend/assets/img/projects/lokruproject/pizzaposter.png',
                'images' => [
                    'frontend/assets/img/projects/lokruproject/pizzaposter.png',
                ],
                'description' => 'A vibrant food poster design for a pizza restaurant.',
                'background' => 'Created as a graphic design practice piece for food and beverage marketing.',
                'challenges' => 'Making food look appetizing through layout, color, and typography choices.',
                'solution' => 'Designed a bold, warm-toned poster with strong visual hierarchy and appetite appeal.',
                'demo_url' => null,
                'github_url' => 'https://github.com/username/ecommerce',
                'figma_url' => null,
            ],
        ];

        return collect($projects)->map(function ($project) {

            $project['thumbnail'] = $this->webp($project['thumbnail']);

            $project['images'] = collect($project['images'])
                ->map(fn($image) => $this->webp($image))
                ->toArray();

            return $project;
        })->toArray();
    }
    public function index()
    {
        $data = [
            'page_title' => 'Home',
            'projects' => collect($this->getProjects())->all(),
        ];
        return view('frontend.pages.Home.index', $data);
    }
    public function projectDetail($id)
    {
        $projects = $this->getProjects();
        $project = collect($projects)->firstWhere('id', (int) $id);
        if (!$project)
            abort(404);
        $prev = collect($projects)->firstWhere('id', (int) $id - 1);
        $next = collect($projects)->firstWhere('id', (int) $id + 1);
        return view('frontend.pages.Home.project-detail', compact('project', 'prev', 'next'));
    }
}
